#!/usr/bin/env bash
# env.sh — source this (`source scripts/env.sh`) so gem5sim uses the tree that
# setup.sh built under ./_work. Regenerated by setup.sh; safe to edit by hand.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export GEM5_DIR="$HERE/_work/gem5"
export NVMAIN_CONFIG="$HERE/_work/NVmain/Config/PCM_ISSCC_2012_4GB.config"
export BENCHMARK_DIR="$HERE/data/benchmarks"
export ANSWER_DIR="$HERE/data"
export PATH="$HERE/scripts:$PATH"
echo "gem5 env ready -> $GEM5_DIR/build/X86/gem5.opt"
