#!/usr/bin/env bash
# setup.sh — build the gem5 + NVMain environment this repo's overlay targets.
#
# What it does (idempotent — safe to re-run):
#   1. Clone gem5 at the pinned commit into ./_work/gem5  (skipped if present)
#   2. Clone NVMain into ./_work/NVmain                   (skipped if present)
#   3. Apply this repo's source overlay onto the full gem5 tree
#   4. Build gem5 with NVMain  ->  ./_work/gem5/build/X86/gem5.opt
#   5. Write ./env.sh so `scripts/gem5sim` points at the freshly built tree
#
# After it finishes:
#   source scripts/env.sh
#   scripts/run_all.sh            # reproduce Q1-Q5
#   # or single questions, e.g.:
#   scripts/gem5sim quicksort --l3 --assoc 2 --save Q3/2way
#
# The heavy step is the gem5 compile (~30-90 min the first time). ./_work is
# git-ignored, so cloning/building never pollutes the committed repo.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$REPO_DIR/_work"

# Pinned upstreams (see gem5/README.md "Source Comparison").
GEM5_REPO="https://github.com/gem5/gem5.git"
GEM5_COMMIT="525ce650e1a5bbe71c39d4b15598d6c003cc9f9e"
NVMAIN_REPO="https://github.com/SEAL-UCSB/NVmain.git"

NVMAIN_CONFIG_REL="Config/PCM_ISSCC_2012_4GB.config"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARNING: %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# --- 0. Toolchain sanity check -------------------------------------------------
say "Checking toolchain"
command -v git    >/dev/null || die "git not found. Install it, or use the Podman image (see README)."
command -v scons  >/dev/null || die "scons not found. Install it, or use the Podman image (see README)."
command -v g++    >/dev/null || die "g++ not found. Install build-essential, or use the Podman image."
if ! command -v python >/dev/null && ! command -v python2 >/dev/null; then
    die "Python 2.7 not found. gem5's SCons build needs Python 2 (Python 3 breaks it)."
fi
echo "  git:   $(command -v git)"
echo "  scons: $(command -v scons)"
echo "  g++:   $(command -v g++)"

mkdir -p "$WORK"

# --- 1. gem5 -------------------------------------------------------------------
if [[ ! -d "$WORK/gem5/.git" ]]; then
    say "Cloning gem5 (this is large; pinned commit ${GEM5_COMMIT:0:12})"
    git clone "$GEM5_REPO" "$WORK/gem5"
    git -C "$WORK/gem5" checkout "$GEM5_COMMIT"
else
    say "gem5 already cloned at $WORK/gem5 (skipping clone)"
fi

# --- 2. NVMain -----------------------------------------------------------------
if [[ ! -d "$WORK/NVmain/.git" ]]; then
    say "Cloning NVMain"
    git clone "$NVMAIN_REPO" "$WORK/NVmain"
else
    say "NVMain already cloned at $WORK/NVmain (skipping clone)"
fi
[[ -f "$WORK/NVmain/$NVMAIN_CONFIG_REL" ]] || \
    warn "Expected $NVMAIN_CONFIG_REL not found under $WORK/NVmain — check the NVMain clone."

# --- 3. Apply the overlay ------------------------------------------------------
say "Applying source overlay onto the full gem5 tree"
cp -rv "$REPO_DIR/gem5/configs" "$REPO_DIR/gem5/src" "$WORK/gem5/" | tail -n 20

# --- 4. Build ------------------------------------------------------------------
say "Building gem5 with NVMain (30-90 min the first time)"
( cd "$WORK/gem5" && scons EXTRAS=../NVmain build/X86/gem5.opt -j"$(nproc)" )
[[ -x "$WORK/gem5/build/X86/gem5.opt" ]] || die "Build finished but gem5.opt is missing."

# --- 5. Emit env.sh ------------------------------------------------------------
say "Writing env.sh"
cat > "$REPO_DIR/scripts/env.sh" <<'EOF'
#!/usr/bin/env bash
# env.sh — source this (`source scripts/env.sh`) so gem5sim uses the tree that
# setup.sh built under ./_work. Regenerated by setup.sh; safe to edit by hand.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export GEM5_DIR="$HERE/_work/gem5"
export NVMAIN_CONFIG="$HERE/_work/NVmain/Config/PCM_ISSCC_2012_4GB.config"
export BENCHMARK_DIR="$HERE/data/benchmarks"
export ANSWER_DIR="$HERE/data"
export PATH="$HERE/scripts:$PATH"
echo "gem5 env ready -> $GEM5_DIR/build/X86/gem5.opt"
EOF

say "Done."
cat <<EOF

Next:
  source scripts/env.sh   # set GEM5_DIR / NVMAIN_CONFIG / PATH for this shell
  scripts/run_all.sh   # reproduce all of Q1-Q5 into data/
  gem5sim --help       # see all wrapper options

EOF
